package bean;

import interfaces.RepresentBehavior;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

import javax.swing.JPanel;

public class GameRepresentation extends JPanel {

  /**
   * 
   */
  private static final long serialVersionUID = -5338428440010515769L;

  protected Board board;
  protected OriginalPattern originalPattern;
  protected RuleType ruleType;
  protected int maxLineWidth;

  private RepresentBehavior behavior;

  private javax.swing.JPanel boardPanel;
  private GridBagConstraints gridBagConstraints;

  public GameRepresentation() {
	initComponents();
  }

  public void setOriginalPattern(OriginalPattern originalPattern) {
	this.originalPattern = originalPattern;
  }

  public void setRuleType(RuleType ruleType) {
	this.ruleType = ruleType;
  }

  public Board getBoard() {
	return board;
  }

  public void setBoard(Board board) {
	this.board = board;
  }

  public void setMaxLineWidth(int maxLineWidth) {
	this.maxLineWidth = maxLineWidth;
  }

  public void init() {
	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 0;
	gridBagConstraints.gridy = 0;
	gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
	gridBagConstraints.weightx = 1.0;
	gridBagConstraints.weighty = 1.0;
	gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);

	boardPanel.add(behavior.getRepresntationContainer(), gridBagConstraints);
  }

  public void calculateNextStatus(Rule rule) {
	board.calculateNextStatus(rule);
  }

  public void repaintBoard() {
	performRepresent();

	repaint();
  }

  public void stop() {
  }

  public RepresentBehavior getBehavior() {
	return behavior;
  }

  public void setBehavior(RepresentBehavior behavior) {
	this.behavior = behavior;
  }

  public void performRepresent() {
	behavior.represent(board);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {
	java.awt.GridBagConstraints gridBagConstraints;

	boardPanel = new javax.swing.JPanel();

	boardPanel.setMaximumSize(new java.awt.Dimension(371, 261));
	boardPanel.setLayout(new java.awt.GridBagLayout());

	GridBagLayout layout = new GridBagLayout();
	this.setLayout(layout);

	gridBagConstraints = new java.awt.GridBagConstraints();
	gridBagConstraints.gridx = 0;
	gridBagConstraints.gridy = 0;
	gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
	gridBagConstraints.weightx = 1.0;
	gridBagConstraints.weighty = 1.0;
	gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
	add(boardPanel, gridBagConstraints);
  }// </editor-fold>

}
